# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpb.proto',
  package='',
  serialized_pb=_b('\n\tgpb.proto\"\xa5\x01\n\rPlayerMessage\x12\x10\n\x08playerId\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06health\x18\x03 \x02(\x05\x12$\n\tinventory\x18\x04 \x02(\x0b\x32\x11.InventoryMessage\x12\"\n\x08location\x18\x05 \x02(\x0b\x32\x10.LocationMessage\x12\x1a\n\x04path\x18\x06 \x02(\x0b\x32\x0c.PathMessage\"\'\n\x0fLocationMessage\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\"\x1f\n\x0bItemMessage\x12\x10\n\x08itemName\x18\x01 \x02(\t\"(\n\nMapMessage\x12\x1a\n\x04room\x18\x01 \x03(\x0b\x32\x0c.RoomMessage\"\xdd\x01\n\x0bRoomMessage\x12\"\n\x08location\x18\x01 \x02(\x0b\x32\x10.LocationMessage\x12,\n\radjacencyList\x18\x02 \x02(\x0b\x32\x15.AdjacencyListMessage\x12$\n\tinventory\x18\x03 \x02(\x0b\x32\x11.InventoryMessage\x12\x0c\n\x04type\x18\x04 \x02(\x05\x12\x0e\n\x06puzzle\x18\x05 \x01(\t\x12\x10\n\x08solution\x18\x06 \x01(\t\x12&\n\nplayerList\x18\x07 \x02(\x0b\x32\x12.PlayerListMessage\"P\n\x14\x41\x64jacencyListMessage\x12\r\n\x05north\x18\x01 \x02(\x05\x12\x0c\n\x04\x65\x61st\x18\x02 \x02(\x05\x12\r\n\x05south\x18\x03 \x02(\x05\x12\x0c\n\x04west\x18\x04 \x02(\x05\"3\n\x11PlayerListMessage\x12\x1e\n\x06player\x18\x01 \x03(\x0b\x32\x0e.PlayerMessage\".\n\x10InventoryMessage\x12\x1a\n\x04item\x18\x01 \x03(\x0b\x32\x0c.ItemMessage\"1\n\x0bPathMessage\x12\"\n\x08location\x18\x01 \x03(\x0b\x32\x10.LocationMessage\"O\n\x0bGameMessage\x12&\n\nplayerList\x18\x01 \x02(\x0b\x32\x12.PlayerListMessage\x12\x18\n\x03map\x18\x02 \x02(\x0b\x32\x0b.MapMessage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERMESSAGE = _descriptor.Descriptor(
  name='PlayerMessage',
  full_name='PlayerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='PlayerMessage.playerId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='PlayerMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='health', full_name='PlayerMessage.health', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='PlayerMessage.inventory', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='PlayerMessage.location', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='PlayerMessage.path', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=179,
)


_LOCATIONMESSAGE = _descriptor.Descriptor(
  name='LocationMessage',
  full_name='LocationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='LocationMessage.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='LocationMessage.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=220,
)


_ITEMMESSAGE = _descriptor.Descriptor(
  name='ItemMessage',
  full_name='ItemMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemName', full_name='ItemMessage.itemName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=253,
)


_MAPMESSAGE = _descriptor.Descriptor(
  name='MapMessage',
  full_name='MapMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room', full_name='MapMessage.room', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=295,
)


_ROOMMESSAGE = _descriptor.Descriptor(
  name='RoomMessage',
  full_name='RoomMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='RoomMessage.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adjacencyList', full_name='RoomMessage.adjacencyList', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='RoomMessage.inventory', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='RoomMessage.type', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='puzzle', full_name='RoomMessage.puzzle', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='RoomMessage.solution', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerList', full_name='RoomMessage.playerList', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=519,
)


_ADJACENCYLISTMESSAGE = _descriptor.Descriptor(
  name='AdjacencyListMessage',
  full_name='AdjacencyListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='north', full_name='AdjacencyListMessage.north', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='east', full_name='AdjacencyListMessage.east', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='south', full_name='AdjacencyListMessage.south', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='west', full_name='AdjacencyListMessage.west', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=601,
)


_PLAYERLISTMESSAGE = _descriptor.Descriptor(
  name='PlayerListMessage',
  full_name='PlayerListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='PlayerListMessage.player', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=654,
)


_INVENTORYMESSAGE = _descriptor.Descriptor(
  name='InventoryMessage',
  full_name='InventoryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='InventoryMessage.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=702,
)


_PATHMESSAGE = _descriptor.Descriptor(
  name='PathMessage',
  full_name='PathMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='PathMessage.location', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=753,
)


_GAMEMESSAGE = _descriptor.Descriptor(
  name='GameMessage',
  full_name='GameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerList', full_name='GameMessage.playerList', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map', full_name='GameMessage.map', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=834,
)

_PLAYERMESSAGE.fields_by_name['inventory'].message_type = _INVENTORYMESSAGE
_PLAYERMESSAGE.fields_by_name['location'].message_type = _LOCATIONMESSAGE
_PLAYERMESSAGE.fields_by_name['path'].message_type = _PATHMESSAGE
_MAPMESSAGE.fields_by_name['room'].message_type = _ROOMMESSAGE
_ROOMMESSAGE.fields_by_name['location'].message_type = _LOCATIONMESSAGE
_ROOMMESSAGE.fields_by_name['adjacencyList'].message_type = _ADJACENCYLISTMESSAGE
_ROOMMESSAGE.fields_by_name['inventory'].message_type = _INVENTORYMESSAGE
_ROOMMESSAGE.fields_by_name['playerList'].message_type = _PLAYERLISTMESSAGE
_PLAYERLISTMESSAGE.fields_by_name['player'].message_type = _PLAYERMESSAGE
_INVENTORYMESSAGE.fields_by_name['item'].message_type = _ITEMMESSAGE
_PATHMESSAGE.fields_by_name['location'].message_type = _LOCATIONMESSAGE
_GAMEMESSAGE.fields_by_name['playerList'].message_type = _PLAYERLISTMESSAGE
_GAMEMESSAGE.fields_by_name['map'].message_type = _MAPMESSAGE
DESCRIPTOR.message_types_by_name['PlayerMessage'] = _PLAYERMESSAGE
DESCRIPTOR.message_types_by_name['LocationMessage'] = _LOCATIONMESSAGE
DESCRIPTOR.message_types_by_name['ItemMessage'] = _ITEMMESSAGE
DESCRIPTOR.message_types_by_name['MapMessage'] = _MAPMESSAGE
DESCRIPTOR.message_types_by_name['RoomMessage'] = _ROOMMESSAGE
DESCRIPTOR.message_types_by_name['AdjacencyListMessage'] = _ADJACENCYLISTMESSAGE
DESCRIPTOR.message_types_by_name['PlayerListMessage'] = _PLAYERLISTMESSAGE
DESCRIPTOR.message_types_by_name['InventoryMessage'] = _INVENTORYMESSAGE
DESCRIPTOR.message_types_by_name['PathMessage'] = _PATHMESSAGE
DESCRIPTOR.message_types_by_name['GameMessage'] = _GAMEMESSAGE

PlayerMessage = _reflection.GeneratedProtocolMessageType('PlayerMessage', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:PlayerMessage)
  ))
_sym_db.RegisterMessage(PlayerMessage)

LocationMessage = _reflection.GeneratedProtocolMessageType('LocationMessage', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessage)
  ))
_sym_db.RegisterMessage(LocationMessage)

ItemMessage = _reflection.GeneratedProtocolMessageType('ItemMessage', (_message.Message,), dict(
  DESCRIPTOR = _ITEMMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:ItemMessage)
  ))
_sym_db.RegisterMessage(ItemMessage)

MapMessage = _reflection.GeneratedProtocolMessageType('MapMessage', (_message.Message,), dict(
  DESCRIPTOR = _MAPMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:MapMessage)
  ))
_sym_db.RegisterMessage(MapMessage)

RoomMessage = _reflection.GeneratedProtocolMessageType('RoomMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROOMMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:RoomMessage)
  ))
_sym_db.RegisterMessage(RoomMessage)

AdjacencyListMessage = _reflection.GeneratedProtocolMessageType('AdjacencyListMessage', (_message.Message,), dict(
  DESCRIPTOR = _ADJACENCYLISTMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:AdjacencyListMessage)
  ))
_sym_db.RegisterMessage(AdjacencyListMessage)

PlayerListMessage = _reflection.GeneratedProtocolMessageType('PlayerListMessage', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERLISTMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:PlayerListMessage)
  ))
_sym_db.RegisterMessage(PlayerListMessage)

InventoryMessage = _reflection.GeneratedProtocolMessageType('InventoryMessage', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage)
  ))
_sym_db.RegisterMessage(InventoryMessage)

PathMessage = _reflection.GeneratedProtocolMessageType('PathMessage', (_message.Message,), dict(
  DESCRIPTOR = _PATHMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:PathMessage)
  ))
_sym_db.RegisterMessage(PathMessage)

GameMessage = _reflection.GeneratedProtocolMessageType('GameMessage', (_message.Message,), dict(
  DESCRIPTOR = _GAMEMESSAGE,
  __module__ = 'gpb_pb2'
  # @@protoc_insertion_point(class_scope:GameMessage)
  ))
_sym_db.RegisterMessage(GameMessage)


# @@protoc_insertion_point(module_scope)
